---
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 5541ec5dcc8ccd55fe5288265090e3d9c5958e04
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 04/23/2019
ms.locfileid: "62550171"
---
# <a name="c26111"></a>C26111
警告 C26111:呼叫端無法釋放鎖定\<鎖定 > 函式的呼叫之前\<l o c k >。

 註釋`_Requires_lock_not_held_`加諸，呼叫此函式時，指定鎖定的鎖定計數不能小於或等於零的前置條件。 當函式無法釋放鎖定，然後呼叫另一個函式時，會發出警告 C26111。

## <a name="example"></a>範例
 下列範例會產生警告 C26111，因為`_Requires_lock_not_held_`的呼叫所違反的前置條件，則`DoNotLock`內鎖定的區段。

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```