---
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 299b2f3918af48e84f74cde5d4d783645491ef5d
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 12/06/2019
ms.locfileid: "74879200"
---
# <a name="c26111"></a>C26111
警告 C26111：呼叫者在呼叫函式 \<func > 之前，無法釋放鎖定 \<鎖定 >。

 注釋 `_Requires_lock_not_held_` 會在呼叫函式時，強加指定鎖定的鎖定計數不能大於零的前置條件。 當函式無法在呼叫另一個函式之前釋放鎖定時，就會發出警告 C26111。

## <a name="example"></a>範例
 下列範例會產生警告 C26111，因為鎖定區段中 `DoNotLock` 的呼叫會違反 `_Requires_lock_not_held_` 的前置條件。

```cpp
typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```
